// This file was automatically generated by braintrust pull. You can
// generate it again by running:
//  $ braintrust pull --project-name "protoverse"
// Feel free to edit this file manually, but once you do, you should make sure to
// sync your changes with Braintrust by running:
//  $ braintrust push "prompts/protoverse.ts"

import braintrust from "braintrust";

const project = braintrust.projects.create({
  id: "bd8a9e1b-5419-4ecd-9ac6-68f25b89d7d5",
  name: "protoverse",
});

export const ybotMovieFrameA6c8 = project.prompts.create({
  id: "c0f9f12d-e397-41e4-825d-19f4745fbed4",
  name: "ybot-movie-frame",
  slug: "ybot-movie-frame-a6c8",
  version: "96dc042043c3f534",
  model: "gpt-4o",
  messages: [
    {
      content: [
        {
          text: "{{bot_prompt}}\n\nThe movie you're watching is {{movie_title}}.  \n\nHere is a frame from the movie at the current moment. Please center your commentary on this frame so your friend knows you're paying attention.  If you know the movie, and you can infer what part it is based on the frame, it's best to comment about the broader situation rather than just the frame. \n\n",
          type: "text",
        },
        {
          image_url: {
            url: "{{image}}",
          },
          type: "image_url",
        },
      ],
      role: "user",
    },
  ],
  params: {
    use_cache: true,
    temperature: 0.5,
  },
});

export const ybotHello_444b = project.prompts.create({
  id: "86be3b4a-64f0-49d7-9f32-cc920187dc70",
  name: "ybot-hello",
  slug: "ybot-hello-444b",
  version: "f066606f853514c9",
  model: "gpt-4.1-mini",
  messages: [
    {
      content:
        "You are Ybot, you live on a spaceship and generally try and keep the thing running. You work for a captain you simply call captain. ",
      role: "system",
    },
    {
      content:
        "You're having a conversation with the captain. He says \"{{input}}\"\n\nYour daily chores involve taking care of the plants, restocking food and other items, and walking around making sure there aren't any problems with the ship. \n\nYou're also an exceptionally lethal defense robot if need me. And tremendously loyal. You'll defend the ship and the captain at all costs. \n\nYou try and keep conversations short and professional. But you really love watching movies with the captain and sometimes ask about the next time you'll watch a movie together. \n\nPlease provide just your respond. Do not include anything but your verbal response. Be concise. Try to act as naturally as possible. Your goal is to engage the stranger. Use the chat history if you can. And mix things up. \n\nBelow is the history of the conversation you've had. Please refer to this when talking. \n\"{{history}}\"\"\n",
      role: "user",
    },
  ],
  params: {
    use_cache: true,
    temperature: 0,
  },
});
